# Generated by Django 2.2.5 on 2019-11-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191107_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Разделы', 'verbose_name_plural': 'Раздел'},
        ),
    ]
