# Generated by Django 2.2.5 on 2019-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20191107_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
