# Generated by Django 2.2.5 on 2019-11-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20191107_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика статьи'},
        ),
    ]
