# Generated by Django 2.2.5 on 2019-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_scope_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
    ]
